version: '3'

services:

  postgreSQL:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=flat_app
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  myapp-main:
    build: .
    restart: on-failure
    depends_on:
      - postgreSQL
    ports:
      - 8889:8080
    environment:
      - DATABASE_HOST=postgreSQL
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=flat_app
      - DATABASE_PORT=5432
      - spring.profiles.active=prod

volumes:
  db-data: {}

