version: '3'

services:

  postgreSQL-demo:
    image: postgres:13-alpine
    ports:
      - 5556:5556
    command: -p 5556
    environment:
      - DEBUG=false
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=flat_app
    volumes:
      - db-data-demo:/var/lib/postgresql/data
    restart: unless-stopped

  myapp-main-demo:
    build: .
    restart: on-failure
    depends_on:
      - postgreSQL-demo
    ports:
      - 8890:8080
    environment:
      - DATABASE_HOST=postgreSQL
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=flat_app
      - DATABASE_PORT=5556
      - spring.profiles.active=prod

volumes:
  db-data-demo: {}

